### ISSUE TITLE
The prefab "Console" is broken.

### ISSUE THREAD

**Issue by zwcloud** [peeweek/net.peeweek.console#1]
![image](https://user-images.githubusercontent.com/6965758/52109256-d2035000-2637-11e9-9541-9fa8ac7d6c66.png)

Renaming the root namespace from `Console` to `Peeweek` could fix the error in the image above. But it will also break the prefab, because script connections to the gameobjects in the prefab are lost after changing the namespace, I think.

Please provide a Unity scene with a correct hierarchy of the console instead of a single prefab file. A working sample scene is also helpful.

PS:
Before renaming the Console namespace, when I removed and then tried to re-add the `Console` script component to the "Console" prefab, an error occurred: `Can't add script behaviour TMP_CoroutineTween. The script needs to derive from MonoBehaviour!`. (The name `TMP_CoroutineTween` seems to be a random name.) It seems a bug in Unity: https://forum.unity.com/threads/cant-add-script-behaviour-tmp_coroutinetween-the-script-needs-to-derive-from-monobehaviour.550183/
![1](https://user-images.githubusercontent.com/6965758/52109593-01ff2300-2639-11e9-9ef9-27ebac96425a.gif)

Environtment: Win10, Unity 2018.2.4f1

**Comment by zwcloud** [comment]
And this:
![2](https://user-images.githubusercontent.com/6965758/52109881-e9dbd380-2639-11e9-823a-a2326342954f.gif)

> Unable to instantiate prefab. Prefab may be broken.
> UnityEditorInternal.InternalEditorUtility:HierarchyWindowDrag(HierarchyProperty, Boolean, HierarchyDropMode)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by peeweek** [comment]
Can you still reproduce this issue while using the new package version? (1.1.0)
Since some time ago the prefab is supposed to instantiate itself so your issue might not be around anymore.

**Comment by zwcloud** [comment]
> Since some time ago the prefab is supposed to instantiate itself so your issue might not be around anymore.

OK. This issue could be closed if you are sure about that.
